##############################
# Country definition for CHC #
##############################
#####################
# Country main data #
#####################

country =
{ tag                    = CHC
  intrinsic_gov_type     = leninist
  capital                = 1271 # Yan'an

	research_mod = 1.10
	peacetime_ic_mod = 1.00
        extra_tc = 50
	tc_mod = 1.10

  # Resource Reserves
  energy                 = 1000
  metal                  = 600
  rare_materials         = 600
  oil                    = 400
  supplies               = 1000
  money                  = 200
  manpower               = 1000
  dissent                = 5
  diplomacy =
  { relation = { tag = JAP value = -200 }
    relation = { tag = MAN value = -100 }
    relation = { tag = CHI value = -200 }
    relation = { tag = CGX value = -200 }
    relation = { tag = CYN value = -200 }
    relation = { tag = CSX value = -200 }
    relation = { tag = CXB value = -200 }
    relation = { tag = U70 value = -120 }
    relation = { tag = U95 value = -120 }
    relation = { tag = SOV value = 100 }
    relation = { tag = MON value = 25 }
    relation = { tag = SIK value = 40 }
    relation = { tag = U01 value = 100 }
  }
   SpyInfo                = {  country = "CHC" NumberOfSpies = 1  } 

  nationalprovinces      = { 1170 1202 1203 1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222
                             1223 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246
                             1247 1248 1249 1250 1251 1252 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266 1267 1268 1269 1270
                             1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281 1282 1283 1293 1294 1305 1307 1308 1309 1310 1311 1312 1313 1314
                             1315 1316 1317 1318 1319 1320 1321 1322 1323 1324 1325 1327 1360 1361 1362 1363 1364 1365 1374 1375 1377 1378 1379 1380
                             1381 1382 1386 1387 1388 1389 1390 1394 1395 1396 1397 1398 1401 1402 1403 1421 1430 1431 2955 2956 2958 2959 2960 2961
                             1432 1433 1435 1439 1440 1441 1442 1443 1444 1445 1446 1447 1448 1450 1451 1452 1453 1455 1530 1595 2963
                             1623 1779 1810 1811 1875 1876 1884 1885 1886 1887 1888 1889 1890 1894 1898 2605 2606 2607 2608 2609 2610 2611 2612 2613
                             2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632 2633 2634 2635 2636 2637
                             2638 2639 2640 2641 2642 2643 2644 2645 2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658 2659 2660 2661
                             2662 2663 2664 2665 2666 2667 2668 2669 2670 2671 2672 2673 2674 2675 2676 2677 2678 2679 2680 2681 2682 2683 2684 2685
                             2686 2687 2688 2689 2690 2691 2692 2693 2694 2695 2696 2697 2698 2699 2700 2701 2702 2703 2704 2705 2706 2707 2708 2709
                             2710 2711 2712 2713 2714 2715 2716 2717 2718 2719 2720 2721 2722 2723 2724 2725 2726 2727 2728 2729 2730 2731 2732 2733
                             2734 2735 2736 2737 2738 2739 2740 2741 2742 2743 2744 2745 2746 2747 2748 2749 2750 2751 2752 2753 2754 2755 2756 2757
                             2758 2759 2760 2761 2762 2763 2764 2765 2766 2767 2768 2769 2770 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781
                             2782 2783 2784 2785 2786 2787 2788 2789 2790 2791 2792 2793 2794 2795 2796 2797 2798 2799 2800 2801 2802 2803 2804 2805
                             2806 2807 2808 2809 2810 2811 2812 2813 2814 2815 2816 2817 2818 2819 2820 2821 2822 2823 2824 2825 2826 2827 2828 2829
                             2830 2831 2832 2833 2834 2835 2836 2837 2838 2839 2840 2841 2842 2843 2844 2845 2846 2847 2848 2849 2850 2851 2852 2853
                             2854 2855 2856 2857 2858 2859 2860 2861 2862 2863 2864 2865 2866 2867 2868 2869 2870 2871 2872 2873 2875 2876 2877 2878
                             2879 2880 2881 2882 2883 2884 2885 2886 2887 2888 2889 2890 2891 2892 2893 2894 2895 2896 2897 2898 2899 2900 2901 2902
                             2903 2904 2905 2906 2907 2908 2909 2910 2911 2912 2913 2914 2915 2916 2917 2918 2919 2920 2921 2922 2923 2924 2925 2926
                             2927 2928 2929 2930 2931 2932 2933 2934 2935 2936 2937 2938 2939 2941 2942 2943 2944 2945 2946 2947 
                             2957 2962 2964 2965 2966 2967 2968 2969 2970 2971 2972 2973 2974 2975 2976 2977 2978 2979 2980 2981
                             2982 2983 2984 2985 2986 2987 2988 2996 2997 2998 2999 3000 3464 3470 3471 3472 3478 3480 3481 3590 3591 3592 3593
                             3594 3767 3768 2874 2990 2991 3669 2992 2993 2994 2995
                           }
  ownedprovinces         = { 1271 2789 2791 2792 2794 2796 }
  controlledprovinces    = { 1271 2789 2791 2792 2794 2796 }
  # Group E 1936 techs
  # ######################
  # GW fighter
  techapps               = { 
                             1010 1100 1830 1840 1560
                             6050 6010 6020
                             7420 1410 
                             5310 1900 
                           }
  blueprints = { }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 9
    free_market       = 2
    freedom           = 2
    professional_army = 10
    defense_lobby     = 10
    interventionism   = 5
  }
  headofstate            = { type = 9 id = 51117 }
  headofgovernment       = { type = 9 id = 51002 }
  foreignminister        = { type = 9 id = 51003 }
  armamentminister       = { type = 9 id = 51004 }
  ministerofsecurity     = { type = 9 id = 51030 }
  ministerofintelligence = { type = 9 id = 51006 }
  chiefofstaff           = { type = 9 id = 51007 }
  chiefofarmy            = { type = 9 id = 51008 }
  chiefofnavy            = { type = 9 id = 51009 }
  chiefofair             = { type = 9 id = 51010 }
  # ######
  # COMMUNSIT CHINA OOB
  # ######
  landunit =
  { location = 1271 # Yan'an
    name     = "红1方面军 "
    leader   = 76324 # Lin biao
    id       = { type = 24000 id = 1 }
    division =
    { experience = 80
      id         = { type = 24000 id = 2 }
      name       = "工农红军第1军团 "
      type       = motorized
      model      = 47
      extra = artillery
    }
    division =
    { experience = 50
      id         = { type = 24000 id = 3 }
      name       = "工农红军第15军团 "
      type       = motorized
      model      = 47
      extra = police
    }
    division =
    { experience = 40
      id         = { type = 24000 id = 4 }
      name       = "工农红军第28军 "
      type       = motorized
      model      = 47
      extra = police
    }
    dig_in   = 20.000
  }
  landunit =
  { location = 2789
    name     = "红4方面军 "
    leader   = 76316 # Xu xiangqian
    id       = { type = 24000 id = 10 }
    division =
    { experience = 60
      id         = { type = 24000 id = 11 }
      name       = "工农红军第4军 "
      type       = motorized
      model      = 47
      extra = artillery
    }
    division =
    { experience = 60
      id         = { type = 24000 id = 12 }
      name       = "工农红军第31军 "
      type       = infantry
      model      = 47
      extra = police
    }
    dig_in   = 20.000
  }
 landunit =
  { location = 2796 
    name     = "中共少年团 "
    id       = { type = 24000 id = 90 }
    division =
    { experience = 40
      id         = { type = 24000 id = 203 }
      name       = "中共少年志愿团 "
		type = infantry
		model = 47
    }
    dig_in   = 20.000
  }
 landunit =
  { location = 2794
    name     = "中共青年团 "
    id       = { type = 24000 id = 91 }
    division =
    { experience = 40
      id         = { type = 24000 id = 204 }
      name       = "中共青年志愿团 "
		type = infantry
		model = 47
    }
    dig_in   = 20.000
  }
 landunit =
  { location = 2792 
    name     = "中央党委直属突击队  "
    id       = { type = 24000 id = 92 }
    division =
    { experience = 40 
      id         = { type = 24000 id = 205 }
      name       = "中央党委直属突击队 "
		type = bergsjaeger
		model = 24
    }
    dig_in   = 20.000
  }
 landunit =
  { location = 1271 
    name     = "中央党委直属先锋队 "
    id       = { type = 24000 id = 93 }
    division =
    { experience = 40  locked = yes
      id         = { type = 24000 id = 206 }
      name       = "中共党员先锋队 "
		type = bergsjaeger
		model = 24
    }
    dig_in   = 20.000
  }

   landunit =
   {  location = 1271
      id = { type = 24000 id = 100 }
      dig_in = 20
                name = "红军前敌指挥部 "
		division = {
		id = { type = 24000 id = 101 }
		name = "工农红军前敌指挥部"
                experience = 80
		type = hq
		model = 0
		strength = 100
		}
	}
   landunit =
   {  location = 1271
      id = { type = 24000 id = 159 }
      dig_in = 20
      name = "中央党部警卫团 "
		division = {
                locked = yes
		id = { type = 24000 id = 160 }
		name = "中央党部警卫团"
                experience = 60
		type = garrison
		model = 2
		strength = 100
		extra = engineer
		brigade_model = 2		
                }
    }
	
########
#预备
########
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 104 }
		name = "靖边党委警卫旅 "
                experience = 40
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1	
	}
landdivision = {
		dormant = yes  locked = yes
   	        id = { type = 24000 id = 161 }
		name = "绥德党委警卫旅 "
                experience = 60		
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1		
	}
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 105 }
		name = "洛川党委警卫旅 "
                experience = 40
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1	
	}
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 1000 }
		name = "山西党委警卫旅 "
                experience = 40
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1	
	}
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 1001 }
		name = "山东党委警卫旅 "
                experience = 40
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1	
	}
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 1002 }
		name = "新四军党委警卫旅 "
                experience = 40
		type = garrison
		model = 1
		strength = 100
                extra = engineer
                brigade_model = 1	
	}
landdivision = {
		dormant = yes  locked = yes
		id = { type = 24000 id = 1003 }
		name = "东北抗联指挥部 "
		type = bergsjaeger
		model = 24
                extra = engineer	
	}
landdivision = {
		dormant = yes
   	        id = { type = 24000 id = 110 }
		name = "八路军120师358旅 "
		type = motorized
		model = 47
		max_strength = 100
		experience = 50
                strength     = 100
                extra = artillery
	}
landdivision = {
		dormant = yes 
   	        id = { type = 24000 id = 111 }
		name = "八路军120师359旅 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = anti_air
	}
landdivision = {
		dormant = yes
   	        id = { type = 24000 id = 112 }
		name = "八路军120师教导团 "
		type = bergsjaeger
		model = 24
		experience = 50
                strength     = 80
                extra = engineer
	}
landdivision = {
		dormant = yes 
   	        id = { type = 24000 id = 113 }
		name = "八路军129师385旅 "
		type = motorized
		model = 47
		max_strength = 100
		experience = 50
                strength     = 100
                extra = engineer
	}
landdivision = {
		dormant = yes 
   	        id = { type = 24000 id = 114 }
		name = "八路军129师386旅 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = police
	}
landdivision = {
		dormant = yes
   	        id = { type = 24000 id = 115 }
		name = "八路军129师教导团 "
		type = bergsjaeger
		model = 24
		experience = 50
                strength     = 80
                extra = engineer
	}
landdivision = {
		dormant = yes
   	        id = { type = 24000 id = 107 }
		name = "八路军115师343旅 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = artillery
                brigade_model = 1
	}
landdivision = {
		dormant = yes
                id = { type = 24000 id = 108 }
		name = "八路军115师344旅 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = anti_air
	}
landdivision = {
		dormant = yes
                id = { type = 24000 id = 109 }
		name = "八路军115师独立团 "
		type = bergsjaeger
		model = 24
		experience = 50
                strength     = 100
                extra = engineer
	}
landdivision = {
		dormant = yes
                id = { type = 24000 id = 116 }
		name = "新四军第一支队 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = anti_air
                brigade_model = 1
	}
landdivision = {
		dormant = yes locked = yes
                id = { type = 24000 id = 117 }
		name = "新四军第二支队 "
		type = bergsjaeger
		model = 24
		max_strength = 100
		experience = 50
                strength     = 100
                extra = anti_air
                brigade_model = 1
	}
landdivision = {
		dormant = yes locked = yes
                id = { type = 24000 id = 118 }
		name = "新四军第三支队 "
		type = motorized
		model = 47
		max_strength = 100
		experience = 60
                strength     = 100
                extra = police
                brigade_model = 0
	}
landdivision = {
		dormant = yes
                id = { type = 24000 id = 119 }
		name = "新四军第四支队 "
		type = motorized
		model = 47
		max_strength = 100
		experience = 60
                strength     = 100
                extra = police
                brigade_model = 0
	}
landdivision = {
		dormant = yes
                id = { type = 24000 id = 125 }
		name = "东北抗联第一路军 "
		type = infantry
		model = 47
		experience = 40
                extra = police	
        }
landdivision = {
		dormant = yes
                id = { type = 24000 id = 126 }
		name = "东北抗联第二路军 "
		type = infantry
		model = 47
		experience = 30
                extra = engineer	
        }


}

