###############################
# Victory points distribution #
###############################

province = { id = 0 points = 20 } # (Embarked)
province = { id = 1 points = 1 } # 雷克雅未克
province = { id = 5 points = 5 } # Scapa Flow
province = { id = 9 points = 2 } # Glasgow
province = { id = 10 points = 2 } # Edinburgh
province = { id = 11 points = 1 } # Sunderland
province = { id = 12 points = 2 } # Manchester
province = { id = 13 points = 1 } # Sheffield
province = { id = 14 points = 5 } # Liverpool
province = { id = 15 points = 1 } # Cardiff
province = { id = 16 points = 5 } # Birmingham
province = { id = 17 points = 2 } # Norwich
province = { id = 19 points = 15 } # London
province = { id = 20 points = 2 } # Dover
province = { id = 21 points = 2 } # Portsmouth
province = { id = 23 points = 2 } # Plymouth
province = { id = 24 points = 1 } # Cork
province = { id = 28 points = 1 } # Belfast
province = { id = 30 points = 5 } # Dublin
province = { id = 31 points = 1 } # Malta
province = { id = 32 points = 1 } # Provo
province = { id = 35 points = 1 } # Nantes
province = { id = 38 points = 1 } # Cherbourg
province = { id = 43 points = 1 } # Dunkerque
province = { id = 44 points = 2 } # Lille
province = { id = 45 points = 2 } # Ghent
province = { id = 46 points = 5 } # Rotterdam
province = { id = 47 points = 15 } # Amsterdam
province = { id = 50 points = 5 } # Antwerp
province = { id = 51 points = 10 } # Brussels
province = { id = 56 points = 15 } # Paris
province = { id = 57 points = 1 } # Orleans
province = { id = 58 points = 1 } # Le Mans
province = { id = 65 points = 5 } # Li鑗e
province = { id = 67 points = 10 } # Essen
province = { id = 68 points = 3 } # Li鑗e
province = { id = 71 points = 1 } # Luxembourg
province = { id = 72 points = 1 } # Metz
province = { id = 73 points = 1 } # Strasbourg
province = { id = 75 points = 5 } # Cologne
province = { id = 76 points = 5 } # Dortmund
province = { id = 80 points = 2 } # Wilhelmshaven
province = { id = 82 points = 2 } # Kassel
province = { id = 86 points = 2 } # Hannover
province = { id = 88 points = 5 } # Hamburg
province = { id = 90 points = 2 } # Kiel
province = { id = 92 points = 1 } # 舝hus
province = { id = 93 points = 1 } # Malm?
province = { id = 98 points = 1 } # G鰐eborg
province = { id = 101 points = 5 } # Stockholm
province = { id = 107 points = 5 } # Oslo
province = { id = 110 points = 1 } # Bergen
province = { id = 113 points = 1 } # Falun
province = { id = 125 points = 1 } # Narvik
province = { id = 126 points = 2 } # 基律纳
province = { id = 129 points = 1 } # 瓦尔德
province = { id = 130 points = 1 } # 罗瓦涅米
province = { id = 132 points = 2 } # 贝柴摩
province = { id = 133 points = 1 } # Murmansk
province = { id = 138 points = 1 } # Vaasa
province = { id = 141 points = 1 } # Turku
province = { id = 142 points = 5 } # Helsinki
province = { id = 145 points = 1 } # Viipuri
province = { id = 163 points = 10 } # Stalingrad
province = { id = 175 points = 15 } # Moscow
province = { id = 187 points = 15 } # Leningrad
province = { id = 194 points = 5 } # Tallinn
province = { id = 197 points = 5 } # Riga
province = { id = 206 points = 1 } # Memel
province = { id = 207 points = 3 } # Kaunas
province = { id = 208 points = 1 } # Wilno
province = { id = 212 points = 5 } # Minsk
province = { id = 219 points = 2 } # Smolensk
province = { id = 233 points = 1 } # Odessa
province = { id = 238 points = 5 } # Kiev
province = { id = 248 points = 2 } # Kharkov
province = { id = 253 points = 1 } # Sevastopol
province = { id = 258 points = 1 } # Rostov
province = { id = 283 points = 1 } # Voronezh
province = { id = 294 points = 3 } # Copenhagen
province = { id = 300 points = 15 } # Berlin
province = { id = 302 points = 1 } # Stettin
province = { id = 303 points = 2 } # Danzig
province = { id = 307 points = 1 } # Poznan
province = { id = 310 points = 5 } # Leipzig
province = { id = 311 points = 1 } # 德累斯顿
province = { id = 312 points = 2 } # Nuremberg
province = { id = 313 points = 2 } # Frankfurt am Main
province = { id = 314 points = 3 } # Stuttgart
province = { id = 316 points = 1 } # Mulhouse
province = { id = 320 points = 1 } # Vichy
province = { id = 325 points = 2 } # Bordeaux
province = { id = 331 points = 1 } # Bilbao
province = { id = 333 points = 1 } # Burgos
province = { id = 334 points = 1 } # La Coru馻
province = { id = 335 points = 1 } # Oporto
province = { id = 336 points = 5 } # Lissabon
province = { id = 341 points = 5 } # Madrid
province = { id = 346 points = 1 } # Huelva
province = { id = 347 points = 2 } # Seville
province = { id = 348 points = 5 } # Gibraltar
province = { id = 352 points = 1 } # Murcia
province = { id = 354 points = 1 } # Val鑞cia
province = { id = 356 points = 1 } # Tarragona
province = { id = 357 points = 2 } # Barcelona
province = { id = 359 points = 1 } # Toulouse
province = { id = 364 points = 5 } # Marseille
province = { id = 367 points = 1 } # Corsica
province = { id = 368 points = 1 } # Genoa
province = { id = 370 points = 5 } # Milan
province = { id = 371 points = 1 } # Trento
province = { id = 376 points = 5 } # Munich
province = { id = 377 points = 1 } # Innsbruck
province = { id = 378 points = 5 } # Venice
province = { id = 382 points = 1 } # Zagreb
province = { id = 384 points = 1 } # Split
province = { id = 386 points = 1 } # Sarajevo
province = { id = 390 points = 1 } # Tirana
province = { id = 396 points = 1 } # Crete
province = { id = 401 points = 5 } # Athens
province = { id = 409 points = 5 } # Istanbul
province = { id = 410 points = 1 } # Kavala
province = { id = 411 points = 1 } # Salonika
province = { id = 412 points = 1 } # Edessa
province = { id = 413 points = 1 } # Skopje
province = { id = 417 points = 5 } # Sofia
province = { id = 418 points = 1 } # Ni?
province = { id = 420 points = 1 } # Pleven
province = { id = 421 points = 1 } # Plovdiv
province = { id = 422 points = 1 } # Varna
province = { id = 423 points = 1 } # Constanta
province = { id = 424 points = 5 } # Bucharest
province = { id = 426 points = 1 } # Craiova
province = { id = 428 points = 1 } # Cluj-Napoca
province = { id = 430 points = 1 } # Bra?ov
province = { id = 431 points = 2 } # Ploesti
province = { id = 433 points = 1 } # Iasi
province = { id = 434 points = 1 } # Chisinev
province = { id = 437 points = 1 } # Izmir
province = { id = 439 points = 1 } # Izmit
province = { id = 444 points = 1 } # Cyprus
province = { id = 445 points = 1 } # Gaziantep
province = { id = 448 points = 3 } # Ankara
province = { id = 450 points = 1 } # Trebizond
province = { id = 453 points = 3 } # Belgrade
province = { id = 456 points = 1 } # Pecs
province = { id = 457 points = 10 } # Budapest
province = { id = 458 points = 1 } # Gy鰎
province = { id = 460 points = 1 } # Graz
province = { id = 462 points = 1 } # Salzburg
province = { id = 463 points = 10 } # Vienna
province = { id = 467 points = 1 } # T醔or
province = { id = 469 points = 5 } # Prague
province = { id = 470 points = 1 } # Pilsen
province = { id = 473 points = 2 } # Breslau
province = { id = 474 points = 1 } # Ostrava
province = { id = 476 points = 5 } # Bratislava
province = { id = 479 points = 2 } # Cracow
province = { id = 482 points = 1 } # Oppeln
province = { id = 483 points = 1 } # Lodz
province = { id = 485 points = 10 } # Warsaw
province = { id = 487 points = 1 } # Lublin
province = { id = 490 points = 1 } # Kosice
province = { id = 493 points = 1 } # Novi Sad
province = { id = 495 points = 1 } # Timisoara
province = { id = 497 points = 1 } # Debrecen
province = { id = 499 points = 1 } # Presov
province = { id = 501 points = 1 } # Lvov
province = { id = 504 points = 1 } # Brest Litovsk
province = { id = 508 points = 1 } # Bialystok
province = { id = 510 points = 5 } # 柯尼斯堡
province = { id = 512 points = 2 } # Bologna
province = { id = 519 points = 15 } # Rome
province = { id = 521 points = 1 } # Naples
province = { id = 523 points = 1 } # Taranto
province = { id = 525 points = 1 } # Palermo
province = { id = 528 points = 5 } # Lyon
province = { id = 530 points = 2 } # Geneva
province = { id = 531 points = 2 } # Turin
province = { id = 532 points = 5 } # Bern
province = { id = 533 points = 3 } # Z黵ich
province = { id = 534 points = 1 } # Sardinia
province = { id = 538 points = 1 } # Bermuda
province = { id = 539 points = 1 } # Managua
province = { id = 540 points = 1 } # 圣何塞
province = { id = 541 points = 5 } # Vancouver
province = { id = 551 points = 3 } # 阿拉斯加半岛
province = { id = 556 points = 1 } # Vancouver Island
province = { id = 562 points = 1 } # Rowne
province = { id = 569 points = 1 } # Winnipeg
province = { id = 576 points = 1 } # Newfoundland
province = { id = 579 points = 1 } # Halifax
province = { id = 585 points = 5 } # Montr閍l
province = { id = 586 points = 5 } # Ciudad de Quebec
province = { id = 588 points = 15 } # Ottawa
province = { id = 589 points = 5 } # Toronto
province = { id = 590 points = 1 } # Windsor
province = { id = 591 points = 1 } # Kingston
province = { id = 595 points = 1 } # Concord
province = { id = 600 points = 5 } # Boston
province = { id = 602 points = 15 } # New York
province = { id = 603 points = 3 } # Newark
province = { id = 606 points = 15 } # Washington D.C.
province = { id = 608 points = 5 } # Philadelphia
province = { id = 613 points = 1 } # Buffalo
province = { id = 614 points = 3 } # Pittsburgh
province = { id = 615 points = 1 } # Cleveland
province = { id = 616 points = 5 } # Detroit
province = { id = 619 points = 1 } # Indianapolis
province = { id = 620 points = 3 } # Chicago
province = { id = 621 points = 1 } # Milwaukee
province = { id = 633 points = 1 } # Norfolk
province = { id = 640 points = 1 } # Louisville
province = { id = 642 points = 1 } # Nashville
province = { id = 644 points = 1 } # Charleston
province = { id = 645 points = 1 } # Columbia
province = { id = 647 points = 1 } # Macon
province = { id = 651 points = 1 } # Miami
province = { id = 654 points = 2 } # Havana
province = { id = 657 points = 1 } # Guant醤amo
province = { id = 662 points = 1 } # Midway Island
province = { id = 663 points = 10 } # Pearl Harbour
province = { id = 667 points = 3 } # Buenos Aires
province = { id = 670 points = 1 } # Atlanta
province = { id = 675 points = 1 } # Jackson
province = { id = 676 points = 1 } # Mobile
province = { id = 680 points = 1 } # New Orleans
province = { id = 684 points = 1 } # Little Rock
province = { id = 688 points = 1 } # Springfield
province = { id = 689 points = 1 } # St. Louis
province = { id = 690 points = 1 } # Kansas City
province = { id = 692 points = 1 } # Des Moines
province = { id = 693 points = 1 } # Minneapolis
province = { id = 698 points = 1 } # Bismarck
province = { id = 707 points = 1 } # Denver
province = { id = 715 points = 2 } # Dallas
province = { id = 716 points = 3 } # Houston
province = { id = 717 points = 1 } # San Antonio
province = { id = 724 points = 1 } # Albuquerque
province = { id = 730 points = 1 } # Phoenix
province = { id = 733 points = 1 } # Salt Lake City
province = { id = 738 points = 1 } # La Paz
province = { id = 749 points = 1 } # Tampico
province = { id = 751 points = 1 } # 瓜达拉哈拉
province = { id = 752 points = 3 } # Mexico City
province = { id = 753 points = 1 } # Puebla
province = { id = 754 points = 1 } # Acapulco
province = { id = 755 points = 1 } # Villahermosa
province = { id = 757 points = 1 } # 危地马拉
province = { id = 759 points = 1 } # 圣萨尔瓦多
province = { id = 760 points = 2 } # Tegucigalpa
province = { id = 761 points = 1 } # San Diego
province = { id = 762 points = 5 } # Los Angeles
province = { id = 764 points = 1 } # Sacramento
province = { id = 765 points = 5 } # San Francisco
province = { id = 771 points = 1 } # Boise
province = { id = 774 points = 1 } # Great Falls
province = { id = 779 points = 1 } # Spokane
province = { id = 780 points = 1 } # Seattle
province = { id = 783 points = 1 } # Portland
province = { id = 787 points = 1 } # Rapid City
province = { id = 789 points = 1 } # Omaha
province = { id = 793 points = 1 } # Tulsa
province = { id = 800 points = 1 } # Greenland
province = { id = 803 points = 1 } # Barranquilla
province = { id = 804 points = 3 } # Maracaibo
province = { id = 811 points = 1 } # Caracas
province = { id = 813 points = 2 } # Bogot?
province = { id = 815 points = 2 } # Quito
province = { id = 816 points = 1 } # Trujillo
province = { id = 818 points = 1 } # Iquitos
province = { id = 822 points = 1 } # Rio Branco
province = { id = 830 points = 2 } # Lima
province = { id = 831 points = 1 } # Arequipa
province = { id = 832 points = 2 } # La Paz
province = { id = 837 points = 2 } # Asunci髇
province = { id = 838 points = 1 } # Sucre
province = { id = 839 points = 2 } # Antofagasta
province = { id = 840 points = 3 } # Santiago
province = { id = 843 points = 1 } # San Miguel de Tucum醤
province = { id = 845 points = 1 } # C髍doba
province = { id = 848 points = 1 } # 阿雷格里港
province = { id = 849 points = 1 } # Montevideo
province = { id = 850 points = 1 } # Concordia
province = { id = 851 points = 1 } # Rosario
province = { id = 852 points = 1 } # Mar del Plata
province = { id = 853 points = 1 } # 布兰卡港
province = { id = 858 points = 1 } # Comodoro Rivadavia
province = { id = 864 points = 1 } # Punta Arenas
province = { id = 866 points = 1 } # Falkland Islands
province = { id = 869 points = 1 } # Falkland Islands
province = { id = 871 points = 1 } # Cuyuni
province = { id = 874 points = 1 } # Paramaribo
province = { id = 875 points = 1 } # Cayenne
province = { id = 879 points = 1 } # Bel閙
province = { id = 881 points = 1 } # Recife
province = { id = 882 points = 1 } # Salvador
province = { id = 883 points = 1 } # Goi醩
province = { id = 884 points = 1 } # Vit髍ia
province = { id = 885 points = 5 } # Rio de Janeiro
province = { id = 886 points = 1 } # S鉶 Paulo
province = { id = 888 points = 1 } # Panam?
province = { id = 889 points = 5 } # 巴拿马运河
province = { id = 890 points = 1 } # Medell韓
province = { id = 891 points = 1 } # Jamaica
province = { id = 892 points = 1 } # Port-au-Prince
province = { id = 894 points = 1 } # Santo Domingo
province = { id = 895 points = 1 } # 波多黎各
province = { id = 900 points = 5 } # Suez
province = { id = 901 points = 1 } # Port Said
province = { id = 903 points = 1 } # Cairo
province = { id = 906 points = 1 } # Alexandria
province = { id = 919 points = 1 } # Tobruk
province = { id = 924 points = 1 } # Bengazi
province = { id = 932 points = 1 } # Tripoli
province = { id = 939 points = 1 } # Tunis
province = { id = 949 points = 1 } # Algiers
province = { id = 958 points = 3 } # Casablanca
province = { id = 977 points = 10 } # 廷巴克图
province = { id = 981 points = 1 } # Dakar
province = { id = 988 points = 1 } # Freetown
province = { id = 992 points = 1 } # Monrovia
province = { id = 993 points = 1 } # 阿比让
province = { id = 1002 points = 2 } # 阿克拉
province = { id = 1008 points = 1 } # 拉各斯
province = { id = 1009 points = 1 } # Kaduna;Kaduna
province = { id = 1030 points = 1 } # 苏丹港
province = { id = 1037 points = 1 } # 吉布提
province = { id = 1046 points = 1 } # Addis Ababa
province = { id = 1056 points = 3 } # 摩加迪沙
province = { id = 1060 points = 1 } # Nairobi
province = { id = 1061 points = 1 } # 蒙巴萨
province = { id = 1066 points = 1 } # Khartoum
province = { id = 1078 points = 1 } # Bangui
province = { id = 1089 points = 1 } # 杜阿拉
province = { id = 1092 points = 1 } # Libreville
province = { id = 1095 points = 1 } # Banana
province = { id = 1096 points = 1 } # Loanda
province = { id = 1110 points = 1 } # Windhoek
province = { id = 1116 points = 2 } # Cape Town
province = { id = 1117 points = 1 } # Port Elisabeth
province = { id = 1119 points = 1 } # Durban
province = { id = 1120 points = 1 } # Johannesburg
province = { id = 1121 points = 3 } # Pretoria
province = { id = 1122 points = 1 } # 马普托
province = { id = 1124 points = 1 } # Bulawayo
province = { id = 1127 points = 1 } # 蒷isabethville
province = { id = 1130 points = 1 } # 贝拉
province = { id = 1137 points = 1 } # Tananarive
province = { id = 1142 points = 1 } # L閛poldville
province = { id = 1146 points = 1 } # Cap Verde Islands
province = { id = 1174 points = 1 } # Shumushushima
province = { id = 1175 points = 1 } # Ocha
province = { id = 1176 points = 1 } # Toyohara
province = { id = 1178 points = 1 } # Asahikawa
province = { id = 1179 points = 1 } # Sapporo
province = { id = 1180 points = 1 } # Sendai
province = { id = 1181 points = 1 } # Akita
province = { id = 1182 points = 1 } # Fukushima
province = { id = 1183 points = 1 } # Niigata
province = { id = 1184 points = 15 } # Tokyo
province = { id = 1185 points = 5 } # Nagoya
province = { id = 1186 points = 5 } # Kanazawa
province = { id = 1187 points = 5 } # Osaka
province = { id = 1188 points = 2 } # 广岛
province = { id = 1189 points = 1 } # Shikoku
province = { id = 1190 points = 2 } # Fukuoka
province = { id = 1191 points = 1 } # Kagoshima
province = { id = 1193 points = 1 } # Okinawa
province = { id = 1194 points = 1 } # 济州
province = { id = 1196 points = 1 } # Busan
province = { id = 1199 points = 1 } # Seoul
province = { id = 1201 points = 1 } # Pyongyang
province = { id = 1202 points = 1 } # Dalian
province = { id = 1203 points = 1 } # 唐山
province = { id = 1204 points = 3 } # 天津
province = { id = 1205 points = 10 } # Beiping
province = { id = 1206 points = 1 } # 张家口
province = { id = 1208 points = 1 } # Hohhot
province = { id = 1209 points = 1 } # datong
province = { id = 1210 points = 1 } # Baoding
province = { id = 1215 points = 3 } # Qingdao
province = { id = 1216 points = 3 } # Jinan
province = { id = 1218 points = 3 } # Xuzhou
province = { id = 1221 points = 1 } # Hefei
province = { id = 1225 points = 1 } # Taiyuan
province = { id = 1228 points = 2 } # Zhengzhou
province = { id = 1232 points = 1 } # Hankou
province = { id = 1235 points = 5 } # Nanjing
province = { id = 1236 points = 1 } # Suzhou
province = { id = 1237 points = 10 } # Shanghai
province = { id = 1238 points = 1 } # Hangzhou
province = { id = 1244 points = 1 } # Fuzhou
province = { id = 1251 points = 1 } # Nanchang
province = { id = 1253 points = 3 } # Wuchang
province = { id = 1255 points = 3 } # Changsha
province = { id = 1257 points = 1 } # 衡阳
province = { id = 1258 points = 1 } # Guilin
province = { id = 1260 points = 1 } # 常德
province = { id = 1266 points = 1 } # Yichang
province = { id = 1269 points = 5 } # Xi'an
province = { id = 1270 points = 1 } # Xianyang
province = { id = 1271 points = 5 } # Yan'an
province = { id = 1273 points = 1 } # Yinchuan
province = { id = 1276 points = 1 } # Lanzhou
province = { id = 1280 points = 5 } # Chongqing
province = { id = 1288 points = 1 } # Chittagong
province = { id = 1291 points = 1 } # Myitkyina
province = { id = 1294 points = 1 } # Baoshan
province = { id = 1295 points = 1 } # Lashio
province = { id = 1296 points = 1 } # Mandalay
province = { id = 1299 points = 3 } # 仰光
province = { id = 1307 points = 1 } # Kunming
province = { id = 1313 points = 5 } # Guangzhou
province = { id = 1315 points = 10 } # Hong Kong
province = { id = 1316 points = 1 } # Macao
province = { id = 1319 points = 1 } # Nanning
province = { id = 1321 points = 1 } # Hainan
province = { id = 1322 points = 1 } # 高雄
province = { id = 1323 points = 5 } # Taipei
province = { id = 1328 points = 2 } # Hanoi
province = { id = 1329 points = 1 } # Vientiane
province = { id = 1337 points = 1 } # Saigon
province = { id = 1340 points = 1 } # Phnom Penh
province = { id = 1343 points = 2 } # Bangkok
province = { id = 1345 points = 1 } # Thom Buri
province = { id = 1348 points = 1 } # Singora
province = { id = 1349 points = 1 } # Alor Star
province = { id = 1350 points = 1 } # Kota Bahru
province = { id = 1351 points = 1 } # Kuantan
province = { id = 1352 points = 1 } # Kuala Lumpur
province = { id = 1353 points = 10 } # Singapore
province = { id = 1355 points = 1 } # Medan
province = { id = 1359 points = 1 } # Oosthaven
province = { id = 1360 points = 1 } # Chengdu
province = { id = 1364 points = 1 } # Guiyang
province = { id = 1372 points = 5 } # 海参崴
province = { id = 1374 points = 1 } # 佳木斯
province = { id = 1375 points = 1 } # 牡丹江
province = { id = 1379 points = 1 } # 哈尔滨
province = { id = 1380 points = 1 } # 齐齐哈尔
province = { id = 1381 points = 1 } # 漠河
province = { id = 1382 points = 1 } # 海拉尔
province = { id = 1384 points = 1 } # 赤塔
province = { id = 1386 points = 1 } # 锡林郭勒
province = { id = 1389 points = 3 } # 沈阳
province = { id = 1390 points = 3 } # 长春
province = { id = 1393 points = 1 } # 新义州
province = { id = 1396 points = 1 } # 锦州
province = { id = 1397 points = 1 } # 承德
province = { id = 1404 points = 1 } # Ulan Bator
province = { id = 1418 points = 1 } # Kyzyl
province = { id = 1420 points = 1 } # Khobdo
province = { id = 1422 points = 1 } # Alma-Ata
province = { id = 1427 points = 1 } # Tashkent
province = { id = 1429 points = 1 } # 比什凯克
province = { id = 1433 points = 1 } # Urumqi
province = { id = 1442 points = 1 } # Golmud
province = { id = 1443 points = 1 } # 西宁
province = { id = 1453 points = 1 } # Lhasa
province = { id = 1455 points = 1 } # Punakha
province = { id = 1457 points = 5 } # Calcutta
province = { id = 1469 points = 5 } # Delhi
province = { id = 1473 points = 1 } # Kathmandu
province = { id = 1475 points = 1 } # Lahore
province = { id = 1480 points = 1 } # Hyderabad
province = { id = 1486 points = 1 } # Kabul
province = { id = 1494 points = 3 } # 卡拉奇
province = { id = 1497 points = 1 } # Bandar Abbas
province = { id = 1500 points = 1 } # Mashhad
province = { id = 1502 points = 5 } # 德黑兰
province = { id = 1504 points = 1 } # 阿布扎比
province = { id = 1505 points = 5 } # Bombay
province = { id = 1509 points = 1 } # 马德拉斯
province = { id = 1517 points = 1 } # Colombo
province = { id = 1525 points = 1 } # Okhotsk
province = { id = 1548 points = 5 } # 新西伯利亚
province = { id = 1552 points = 5 } # 鄂木斯克
province = { id = 1567 points = 1 } # 乌法
province = { id = 1572 points = 5 } # 斯维尔德洛夫斯克
province = { id = 1574 points = 1 } # 车里亚宾斯克
province = { id = 1577 points = 1 } # 奥尔斯克
province = { id = 1599 points = 1 } # Iwo Jima
province = { id = 1605 points = 1 } # 马朱罗环礁
province = { id = 1608 points = 1 } # Kwajalein
province = { id = 1611 points = 1 } # Nauru
province = { id = 1613 points = 1 } # Truk
province = { id = 1621 points = 1 } # Palau
province = { id = 1623 points = 1 } # 大庆
province = { id = 1624 points = 1 } # Guam
province = { id = 1627 points = 1 } # Saipan
province = { id = 1628 points = 3 } # 雅加达
province = { id = 1632 points = 1 } # 雅加达
province = { id = 1640 points = 1 } # Makassar
province = { id = 1641 points = 1 } # 马辰
province = { id = 1644 points = 1 } # Kuching
province = { id = 1658 points = 1 } # East Timor
province = { id = 1665 points = 1 } # Hollandia
province = { id = 1670 points = 1 } # Rabaul
province = { id = 1672 points = 1 } # Lae
province = { id = 1674 points = 1 } # 马老奇
province = { id = 1679 points = 5 } # 莫尔兹比
province = { id = 1682 points = 1 } # Bougainville
province = { id = 1685 points = 1 } # Guadalcanal
province = { id = 1692 points = 1 } # Noumea
province = { id = 1696 points = 1 } # Townsville
province = { id = 1703 points = 1 } # Darwin
province = { id = 1712 points = 1 } # Perth
province = { id = 1722 points = 1 } # Brisbane
province = { id = 1724 points = 1 } # Newcastle
province = { id = 1727 points = 5 } # Sydney
province = { id = 1728 points = 5 } # Canberra
province = { id = 1729 points = 1 } # Tasmania
province = { id = 1730 points = 3 } # Melbourne
province = { id = 1733 points = 1 } # Adelaide
province = { id = 1734 points = 1 } # Broken Hill
province = { id = 1735 points = 1 } # Palawan
province = { id = 1737 points = 1 } # Manila
province = { id = 1745 points = 1 } # Leyte
province = { id = 1749 points = 1 } # Cagayan
province = { id = 1752 points = 1 } # Fiji
province = { id = 1756 points = 1 } # Samoa
province = { id = 1763 points = 1 } # Christmas Island
province = { id = 1769 points = 1 } # Tarawa
province = { id = 1786 points = 1 } # Wake Island
province = { id = 1792 points = 1 } # Damascus
province = { id = 1794 points = 1 } # 贝鲁特
province = { id = 1797 points = 5 } # Jerusalem
province = { id = 1799 points = 1 } # 加沙
province = { id = 1807 points = 2 } # Riyadh
province = { id = 1812 points = 1 } # Sanaa
province = { id = 1813 points = 1 } # Aden
province = { id = 1817 points = 1 } # Diego Garcia Island
province = { id = 1819 points = 1 } # Mascate
province = { id = 1820 points = 1 } # 多哈
province = { id = 1821 points = 1 } # Dammam
province = { id = 1822 points = 1 } # Kuweit City
province = { id = 1823 points = 2 } # 巴士拉
province = { id = 1825 points = 2 } # Abadan
province = { id = 1828 points = 2 } # Kuybyshev
province = { id = 1847 points = 1 } # Grozny
province = { id = 1859 points = 1 } # Tabriz
province = { id = 1864 points = 1 } # Mosul
province = { id = 1866 points = 2 } # Baghdad
province = { id = 1867 points = 1 } # The Azores
province = { id = 1868 points = 1 } # Auckland
province = { id = 1871 points = 5 } # Wellington
province = { id = 1872 points = 1 } # Christchurch
province = { id = 1907 points = 5 } # 巴库
province = { id = 2660 points = 1 } # 汉阳
province = { id = 2706 points = 1 } # 金门
province = { id = 2760 points = 1 } # 腾冲
province = { id = 2813 points = 1 } # 包头
province = { id = 2836 points = 1 } # 中条山
province = { id = 2854 points = 1 } # 台儿庄
province = { id = 2861 points = 1 } # 威海卫
province = { id = 2930 points = 2 } # 旅顺港
province = { id = 2966 points = 1 } # Monyu
province = { id = 2987 points = 1 } # Aksai Chin
province = { id = 2989 points = 1 } # Wakhan Corridor
province = { id = 3054 points = 1 } # Verdun
province = { id = 3077 points = 5 } # Easten Berlin
province = { id = 3180 points = 1 } # Pest
province = { id = 3202 points = 1 } # Fiume
province = { id = 3222 points = 1 } # Cetinje
province = { id = 3631 points = 1 } # Fiume
province = { id = 3632 points = 1 } # Cetinje
province = { id = 3639 points = 1 } # Cetinje
province = { id = 3741 points = 1 } # 斯里巴加湾
province = { id = 3911 points = 1 } # 麦加
province = { id = 4057 points = 2 } # 贝洛奥里藏特